### ISSUE TITLE
Field nullability is checking backing fields for properties

### ISSUE THREAD

**Issue by johnendev** [ulrichb/ImplicitNullability#10]
Field nullability is showing warnings on instance and static constructors when the class has auto-properties defined.
```c#
class Foo
{
    public string Bar { get; set; }
    public Foo()
    {
        this.Bar = "";
    }
}
```
``Field '<Bar>k__BackingField' marked with 'NotNull' attribute is not initialized on all execution paths``

**Comment by ulrichb** [comment]
Thanks for your report. Fixed in 3.5.1 (resp. 3.6.0pre02 for R# 2017.1).
