### ISSUE TITLE
ReSharper 2017.1

### ISSUE THREAD

**Issue by matkoch** [ulrichb/ImplicitNullability#12]
ReSharper 2017.1 was released a few seconds ago. Please update A$AP.

**Comment by ulrichb** [comment]
I promise: Update will be released in a shorter interval as the one between VS 2017 release and R# 2017.1.

:P 😄

**Comment by matkoch** [comment]
![264](https://cloud.githubusercontent.com/assets/5005566/24645626/2f4f8c20-1919-11e7-8511-1099b16a5715.jpg)

**Comment by fschmied** [comment]
I'm confused. What is ReSharper?

**Comment by fschmied** [comment]
I'm confused, what is a ReSharper? Just use IN without ReSharper and you'll be fine.

**Comment by ulrichb** [comment]
=> 3.6.0
