### ISSUE TITLE
Selectively reverting to Resharper default nullability?

### ISSUE THREAD

**Issue by jklw** [ulrichb/ImplicitNullability#15]
Hi,
thanks for this extension. I'm using it and enjoying the boilerplate reduction :)

One little issue: For generic data-structure-type things, e.g.
```c#
class Foo<T>
{
  public void AddItem(T t) { [...] }
  public T GetItem() { [...] }
}
```
, neither the implicit `[NotNull]` nor `[CanBeNull]` are optimal if the type is sometimes used with nullable items, and sometimes with items which must not be null.

If we leave `AddItem` and `GetItem` implicitly `[NotNull]`, adding null items of course violates the contract, so there will be warnings, and checking the result of `GetItem` for null will cause specious "Condition is always false/true" and "code is heuristically unreachable" warnings. But if we make them `[CanBeNull]`, there is an annoying warning whenever we use the result of `GetItem`, even if we know that this particular instance only contains non-nullable items.

I think Resharper's default "unknown" nullability is preferable in a case like this, so maybe there should be some attribute (`[UnspecifiedNullability]`?) to revert to that?

Of course, leaving the nullability unspecified is just sweeping the problem under the rug. A real solution would require "higher-order nullability", which I suppose is out-of-scope for this project and would have to go into Resharper itself. Something like:

```c#
[NullabilityParameter("N")]
class Foo<T>
{
  public void AddItem([Nullability("N")] T t) { [...] }

  [Nullability("N")]
  public T GetItem() { [...] }
}

void Something(
  [NullabilityArgument("N = NotNull")] Foo<string> foo1,
  [NullabilityArgument("N = CanBeNull")] Foo<string> foo2)
{
  foo1.Add(null); // Warning
  foo2.Add(null); // OK
}
```
(These are actually unrelated to generic type parameters; the example would make sense even if the item type of `Foo` was fixed to `string`)

Edit: Considering that non-nullable reference types might be coming to C# in the future, I guess it's not worth thinking about this too much.

**Comment by ulrichb** [comment]
This is a good feature idea, and I also planned to implement it, but never had enough use cases to find some motivation to implement it.

As Implicit Nullability will reach its end of life, I'm going to close this issue.
