### ISSUE TITLE
Bug for properties nullability

### ISSUE THREAD

**Issue by DmitryZyr** [ulrichb/ImplicitNullability#18]
Hello! Thank you for your extension. I noticed that some functionality were broken. It's about properties nullability.
My version of extension: 4.2.0.11360173. My version of resharper: 2017.3.3
![bug](https://user-images.githubusercontent.com/3765852/37761926-ce937dfe-2ddc-11e8-99e4-c0402fd8ae83.PNG)

**Comment by ulrichb** [comment]
Hi Dimitry. Thanks for your report.

There is an own configuration to enable/disable properties. Could you check the Implicit Nullability options page in the R# settings, resp. could you post your AssemblyMetadata attributes (if you use configuration by code)? Note that you have to refresh the solution cache after changing the configuration.

**Comment by DmitryZyr** [comment]
Thank you! Your advice was helped!
