### ISSUE TITLE
Integration into ReSharper CLT?

### ISSUE THREAD

**Issue by iluuu1994** [ulrichb/ImplicitNullability#19]
Sorry, I know this is the wrong place to ask this question but the JetBrains team was of little help.

I'm trying to integrate ImplicitNullability into our CI pipeline. Apparently, JetBrains removed the support for the `/x` extension argument. Here's what [they say it should support](https://youtrack.jetbrains.com/issue/RSRP-436208#comment=27-1667146):

> (1) .nupkg auto-expansion: if a Nuget package (.nupkg ) file is found on startup in the product folder, it would be expanded automatically (into a shadow location), and its assemblies used with the product.
> 
> This means that a plugin .nupkg package could be put into the tool folder, and it will be loaded and used automatically. 

This is doing absolutely nothing for me. I tried adding the ImplicitNullability.nupkg to the solution folder and all project folders but nothing is happening.

Have you tried this before? Do you have any idea whats going on?

Thank you for this fantastic library!

**Comment by iluuu1994** [comment]
Oh sorry, I'm a complete moron. That didn't even cross my mind 🤦‍♂️ Thanks for your help!

**Comment by zhengt66** [comment]
Hi, I'm currently trying to get ImplicitNullability to work with CLT. I copied my ImplicitNullability.nupkg into the same folder as my InspectCode.exe, but it gives me errors in the XML output as if the extension wasn't there. The inspection works correctly in Visual Studio 15.

>with a version corresponding to InspectCode => note the postfix of the IN version

I'm not sure what you mean by this, could you please explain how I need to match the version numbers together? I currently have CLT 2018.2.1 and ImplicitNullability 4.5.1.12340181.

**Comment by matkoch** [comment]
4.5.1.12340*181* is compatible with 2018.1
