### ISSUE TITLE
Support for R# 2016.1

### ISSUE THREAD

**Issue by drewnoakes** [ulrichb/ImplicitNullability#2]
Now that it's RTM, I'd like to use this extension with 2016.1.

Any idea when it'll be updated?

Thanks!

**Comment by sheitmann** [comment]
ReSharper 2016.1 has a new option for null analysis mode:
Implicit [NotNull]: only when entity have explicit [CanBeNull] attribute (EXPERIMENTAL).

So the analysis itself seems now integrated into ReSharper itself, however not sure about the possible quick fix or additional checks and warnings ImplicitNullability provides.

**Comment by drewnoakes** [comment]
@sheitmann thanks very much. I'll check this out! It'd still be great to control this at the assembly level via an assembly attribute (see #3).

**Comment by ulrichb** [comment]
I've just released a [pre-release version](https://resharper-plugins.jetbrains.com/packages/ReSharper.ImplicitNullability/3.0.0.20161-beta1) with R# 2016.1 support.

**Comment by ulrichb** [comment]
R# 2016.1 support has been added in v3.0.0.

**Comment by fschmied** [comment]
@sheitmann

> ReSharper 2016.1 has a new option for null analysis mode:

However, this option doesn't allow being turned on for methods, but off for properties. This (besides the additional inspection warnings) is one benefit of still using ImplicitNullability.

**Comment by sheitmann** [comment]
@fschmied 
I'm using ImplicitNullability too because it contains more features and does not show me messages the other devs could misinterpret.
I used the built in version of R# only the few days ImplicitNullability wasn't available ;)

So keep up the great work @ulrichb :)

**Comment by drewnoakes** [comment]
I did check out R#'s own implicit not-null and, as it says in the options dialog, it's definitely experimental. Plenty of false flags and gotchas. There's still a lot of room in this space.

The Roslyn team is also considering adding this to the language itself. This may be what motivated R# to add the option.

https://github.com/dotnet/roslyn/issues/5032

TypeScript is shipping a good solution to nullability in the upcoming 2.0. I hope we'll see support in the language directly one day.

But that would still be several years off. There's definitely a need for this awesome extension.

So thanks again to @ulrichb :)

**Comment by ulrichb** [comment]
@sheitmann, @drewnoakes Thanks!

Yeah. I'm also looking forward to seeing the "Non-nullable types" in TypeScript 2.0.

Unfortunately, the "Non-nullable ref types" in C# have been postponed to "C# 7 + 1" :(

**Comment by drewnoakes** [comment]
Seems that R# has now removed the experimental implicit not-null option. Thanks for continuing your work on this extension.

**Comment by ulrichb** [comment]
In R# 2017.1 this option hasn't been completely removed. JB changed it to be available only in the ["internal mode"](https://www.jetbrains.com/help/resharper/sdk/Extensions/InternalMode.html). 

Just to be sure: Are you asking for a release of the 3.6.0 features for R# 2016.1? (I dropped R# 2016.1 support in the current version.)

**Comment by drewnoakes** [comment]
Interesting. I wondered whether it still respected the value in my `.DotSettings` file even if not in internal mode.

I'm on 2017.1 so am fine without 2016.1, thanks.
