### ISSUE TITLE
Support R# 2019.1

### ISSUE THREAD

**Issue by tom-englert** [ulrichb/ImplicitNullability#26]
Would be cool to have it already for the 2019.1 EAP, else we could not test it.

**Comment by ulrichb** [comment]
Hi, I have already created a branch. [Here is the corresponding build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=OpenSourceProjects_ImplicitNullability_Ci&branch_OpenSourceProjects_ImplicitNullability=RS191&tab=buildTypeStatusDiv).

You can download the .nupkg ending with `...191-pre.nupkg` from the artifacts and use a file system package source in the extension manager settings to install it in ReSharper to test it already in the EAP versions. For Rider use the .zip file from the artifacts.

No guarantees. Haven't tested it manually yet. Automated tests are all green.

**Comment by tom-englert** [comment]
:+1: seems to work fine, did not find any problems yet...

**Comment by ulrichb** [comment]
Nice. Thanks for testing!
