### ISSUE TITLE
Implicit nullability for static readonly fields and properties

### ISSUE THREAD

**Issue by tom-englert** [ulrichb/ImplicitNullability#27]
Static members are almost always not null, but the system types don't have proper external annotations, and JetBrains does not seem to fix this ever. (https://github.com/JetBrains/ExternalAnnotations/issues/75, https://youtrack.jetbrains.com/issue/RSRP-464475, comments in https://www.jetbrains.com/help/resharper/Code_Analysis__External_Annotations.html)

Same applies to generated code (e.g. `Settings.Default`), which is assumed to be `[CanBeNull]` by implicit nullability, but in fact is `[NotNull]`

It would be a very helpful if static readonly fields and properties of external libraries and generated code would default to [NotNull] even if they have no annotations.

**Comment by ulrichb** [comment]
Hmm .. I don't quite understand.

> e.g. Settings.Default, which is assumed to be [CanBeNull] by implicit nullability.

Nope, ... Implicit Nullabilty _either_ annotates it as NotNull (depending on its settings) _or_ uses the default ("unknown") nullability in this case - it doesn't annotate CanBeNull.

Did you enable R#'s "pessimistic value analysis"?  This is a R# feature, not a one of Implicit Nullability - it's even some (non-compatible) alternative.



As `Setting.Default` is "auto-generated" code, Implicit Nullability excludes it by default completely. If you still want to include it, you need the following settings.

![image](https://user-images.githubusercontent.com/388796/58016940-51d9fb00-7aff-11e9-9ca5-5c636e0a7f50.png)

... then you get a implicit [NotNull], as the static `Settings.Default` property is a getter-only prop:

![image](https://user-images.githubusercontent.com/388796/58017216-e80e2100-7aff-11e9-99a2-5f87a386f032.png)

**Comment by tom-englert** [comment]
Yep, I had "pessimistic value analysis" on, didn't realize this had this side effects.
Sorry for bothering...

**Comment by ulrichb** [comment]
Okay that's an explanation. No prob.
