### ISSUE TITLE
Implicit NotNull for properties

### ISSUE THREAD

**Issue by srollinet** [ulrichb/ImplicitNullability#7]
Is there a reason to not consider properties as NotNull implicitly? I have seen that you are adding support for fields, so why not properties?)

As Fody NullGuard also adds null checks for properties, it would be great to have the same behavior in order to be consistent between the static check and the runtime check.

**Comment by ulrichb** [comment]
Hi @srollinet,

Properties are not yet supported, but will be definitely in the future. And yes, fields are the next step and the [branch](https://github.com/ulrichb/ImplicitNullability/tree/FieldsSupport) is almost ready to merge.

The reason why they weren't hi prio for me is that until now there was no project which requested it (only method in/out values).

**Comment by cmeeren** [comment]
I'd like to see support for properties too.

**Comment by ulrichb** [comment]
Released fields support with 3.5.0. Properties will follow but take a while. There will be a lot of (inheritance) test cases ...

**Comment by cmeeren** [comment]
I'm really keen on seeing property support. Is there anything I can do to help speed this up?

**Comment by cmeeren** [comment]
Again, I want to ask: Is there anything anyone else can assist with to speed this up?

**Comment by ulrichb** [comment]
@cmeeren: Properties support is almost finished. I'd be happy if you find time to test it (from the [CI build artifact](https://github.com/ulrichb/ImplicitNullability/issues/7#issuecomment-270696016)) and give feedback.

**Comment by cmeeren** [comment]
@ulrichb Great! Unfortunately I will be away on holiday for some weeks, so I probably won't have time to test it for a while.

**Comment by ulrichb** [comment]
Released with 4.0.0
