### ISSUE TITLE
"void" in "async void" detected as implicit/explicit NotNull

### ISSUE THREAD

**Issue by cmeeren** [ulrichb/ImplicitNullability#8]
![void](https://cloud.githubusercontent.com/assets/7766733/23380897/d520dd0a-fd3c-11e6-974f-8aec3533ce50.png)

**Comment by ulrichb** [comment]
Hi. Thanks for your report. Fixed on [dev branch](https://github.com/ulrichb/ImplicitNullability/tree/dev).

**Comment by ulrichb** [comment]
Released with 3.5.0.
