### ISSUE TITLE
Handle Nullable<> in generic Methods

### ISSUE THREAD

**Issue by bearbytes** [ulrichb/ImplicitNullability#9]
If I use the `Nullable<T>` (or `T?`) type, I implicitly state the possibility of null values, otherwise I would just use `T`.

This is detected correctly by the analyzer, so this works:
```c#
int? myInt;
void Allowed()
{
    myInt = new int?();
}
```

However, when I use `T?` as a generic argument for a method, the analyzer gets confused.
```c#
int? myInt;

T Forward<T>(T value)
{
    return value;
}

void Disallowed()
{
    // Possible 'null' assignment to entity marked with 'NotNull' attribute
    myInt = Forward(new int?());
}
```

I would have to mark my generic method accordingly:
```c#
int? myInt;

[CanBeNull] T Forward<T>([CanBeNull] T value)
{
    return value;
}

void Allowed()
{
    myInt = Forward(new int?());
}
```

However, I would then allow nullability for reference types using this method, which I do not want.

The analyzer should allow null arguments and null return values in generic methods, if they use a `Nullable<>` type.

**Comment by ulrichb** [comment]
It was a conscious decision to make unconstrained generic types implicit [NotNull]. It's a tade-off between the false positives you discovered and false negatives for reference type usages (+ for parity with Fody NullGuard). See [this test](https://github.com/ulrichb/ImplicitNullability/blob/f905e3f9a00b16a8e7172e8d9905f2696654efbe/Src/ImplicitNullability.Samples.Consumer/NullabilityAnalysis/GenericsSampleTests.cs#L33-L42) and the corresponding [GenericsSample](https://github.com/ulrichb/ImplicitNullability/blob/8d8ef6f73980542b8f7ca983d17a30c8a6a74097/Src/ImplicitNullability.Samples.CodeWithIN/NullabilityAnalysis/GenericsSample.cs).

But there is a workaround to fix you issue by defining an overload for the nullable structs:

![image](https://cloud.githubusercontent.com/assets/388796/23592765/052e2458-0206-11e7-825d-2d3dd0854f71.png)

**Comment by ulrichb** [comment]
Closed after long period of inactivity of question.
